/**
 * ============================================================================
 * FULL-STACK E-COMMERCE TECH STORE SEEDER SCRIPT
 * Populates MongoDB Atlas with 100+ realistic electronics & tech gear
 * Also creates a default admin user for testing.
 *
 * Run with: node seeder.js
 * Or: npm run data:import
 * Destroy with: node seeder.js --destroy
 * ============================================================================
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/techvault';

// ─── INLINE SCHEMAS (Self-contained for standalone execution) ────────────────

const UserSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    password: { type: String, required: true, select: false },
    role: { type: String, enum: ['user', 'admin'], default: 'user' },
    addresses: [{ fullName: String, phone: String, street: String, city: String, state: String, zipCode: String, country: String, isDefault: { type: Boolean, default: false } }],
    wishlist: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }],
    refreshToken: { type: String, select: false },
    isActive: { type: Boolean, default: true },
    avatar: { type: String, default: '' },
  },
  { timestamps: true }
);

const ProductSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    slug: { type: String, required: true, unique: true, lowercase: true },
    brand: { type: String, required: true },
    category: {
      type: String,
      required: true,
      enum: ['mobiles', 'laptops', 'tablets', 'audio', 'pc-components', 'gaming-gear'],
    },
    price: { type: Number, required: true },
    discountPrice: { type: Number, default: 0 },
    stock: { type: Number, required: true, default: 10 },
    images: [{ type: String, required: true }],
    description: { type: String, required: true },
    specs: { type: Map, of: String },
    rating: { type: Number, default: 4.8 },
    numReviews: { type: Number, default: 24 },
    isFeatured: { type: Boolean, default: false },
  },
  { timestamps: true }
);

const User = mongoose.models.User || mongoose.model('User', UserSchema);
const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

// ─── 4K RETINA CURATED IMAGE REPOSITORY ──────────────────────────────────────
const IMG = {
  iphone_titanium: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=2000&q=90',
  samsung_ultra: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=2000&q=90',
  pixel_phone: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=2000&q=90',
  gaming_phone: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=2000&q=90',
  minimal_phone: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=2000&q=90',
  macbook_spaceblack: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=2000&q=90',
  dell_xps: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=2000&q=90',
  gaming_laptop: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=2000&q=90',
  ultrabook: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=2000&q=90',
  ipad_pro: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=2000&q=90',
  tablet_stylus: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?auto=format&fit=crop&w=2000&q=90',
  surface_pro: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=2000&q=90',
  sony_anc: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=2000&q=90',
  airpods_max: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=2000&q=90',
  audiophile_openback: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=2000&q=90',
  tws_earbuds: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=2000&q=90',
  rtx_gpu: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=2000&q=90',
  motherboard_rig: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=2000&q=90',
  ram_liquid_cooler: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=2000&q=90',
  nvme_ssd: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=2000&q=90',
  mechanical_keyboard: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=2000&q=90',
  gaming_mouse: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=2000&q=90',
  curved_monitor: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=2000&q=90',
  stream_setup: 'https://images.unsplash.com/photo-1600861194942-f883de0dfe96?auto=format&fit=crop&w=2000&q=90',
};

// ─── MASTER CATALOG (105 products) ───────────────────────────────────────────
const rawCatalog = [
  // ==================== MOBILES (18) ====================
  { title: 'Apple iPhone 16 Pro Max', brand: 'Apple', category: 'mobiles', price: 1199, discountPrice: 1149, stock: 25, images: [IMG.iphone_titanium, IMG.minimal_phone], description: 'Forged in Grade 5 Titanium with the breakthrough A18 Pro Bionic chip, 48MP Fusion camera with 5x telephoto, and dedicated Capture Button.', specs: { Chipset: 'Apple A18 Pro (3nm)', RAM: '8GB LPDDR5X', Storage: '256GB NVMe', Display: '6.9" Super Retina XDR OLED, 120Hz ProMotion', Battery: '4685 mAh (30W Wired, 25W MagSafe)', OS: 'iOS 18 with Apple Intelligence' }, rating: 4.9, numReviews: 87, isFeatured: true },
  { title: 'Samsung Galaxy S24 Ultra 5G', brand: 'Samsung', category: 'mobiles', price: 1299, discountPrice: 1199, stock: 20, images: [IMG.samsung_ultra, IMG.gaming_phone], description: 'Titanium chassis with built-in S-Pen, powered by Snapdragon 8 Gen 3 for Galaxy and Galaxy AI live translation and photo editing.', specs: { Chipset: 'Qualcomm Snapdragon 8 Gen 3 for Galaxy', RAM: '12GB LPDDR5X', Storage: '512GB UFS 4.0', Display: '6.8" Dynamic AMOLED 2X, QHD+, 1-120Hz, 2600 nits', Camera: '200MP Main + 50MP 5x Periscope + 10MP 3x + 12MP Ultra-wide', Battery: '5000 mAh (45W Fast Charging)' }, rating: 4.9, numReviews: 104, isFeatured: true },
  { title: 'Google Pixel 9 Pro XL', brand: 'Google', category: 'mobiles', price: 1099, discountPrice: 999, stock: 18, images: [IMG.pixel_phone, IMG.minimal_phone], description: 'The pinnacle of computational photography and Google Gemini Nano on-device AI with custom Tensor G4 silicon.', specs: { Chipset: 'Google Tensor G4 with Titan M2 security', RAM: '16GB LPDDR5X', Storage: '256GB UFS 3.1', Display: '6.8" Super Actua OLED, 1-120Hz LTPO, 3000 nits peak', OS: 'Android 15 (7 years OS & Security updates)', Battery: '5060 mAh (37W Fast Charge)' }, rating: 4.8, numReviews: 62, isFeatured: false },
  { title: 'OnePlus 12 5G Silky Black', brand: 'OnePlus', category: 'mobiles', price: 799, discountPrice: 749, stock: 30, images: [IMG.minimal_phone, IMG.gaming_phone], description: 'Flagship killer featuring 4th Gen Hasselblad Camera System, 5400mAh battery, and blistering 100W SUPERVOOC charging.', specs: { Chipset: 'Snapdragon 8 Gen 3', RAM: '16GB LPDDR5X', Storage: '512GB UFS 4.0', Display: '6.82" 2K 120Hz ProXDR with Aqua Touch', Battery: '5400 mAh (100W Wired, 50W AIRVOOC)' }, rating: 4.7, numReviews: 45 },
  { title: 'ASUS ROG Phone 8 Pro Gaming Mobile', brand: 'ASUS', category: 'mobiles', price: 1199, discountPrice: 1149, stock: 12, images: [IMG.gaming_phone, IMG.samsung_ultra], description: 'Ultimate mobile gaming flagship with AniMe Vision programmable mini-LED rear display and ultrasonic AirTrigger shoulder buttons.', specs: { Chipset: 'Snapdragon 8 Gen 3 overclocked', RAM: '24GB LPDDR5X', Storage: '1TB UFS 4.0', Display: '6.78" FHD+ Samsung E6 AMOLED 165Hz, 1ms', Cooling: 'GameCool 8 360-degree SoC cooling system', Battery: '5500 mAh with Quick Charge 5.0' }, rating: 4.9, numReviews: 38, isFeatured: true },
  { title: 'Xiaomi 14 Ultra Leica Edition', brand: 'Xiaomi', category: 'mobiles', price: 1249, discountPrice: 1199, stock: 14, images: [IMG.minimal_phone, IMG.iphone_titanium], description: 'Quad Leica 50MP optical system with 1-inch Sony LYT-900 sensor and stepless variable aperture (f/1.63 - f/4.0).', specs: { Chipset: 'Snapdragon 8 Gen 3', RAM: '16GB LPDDR5X', Storage: '512GB UFS 4.0', Display: '6.73" WQHD+ AMOLED 120Hz, 68 Billion Colors', Camera: 'Leica Quad-Camera All 50MP', Battery: '5000 mAh (90W HyperCharge, 80W Wireless)' }, rating: 4.8, numReviews: 29 },
  { title: 'Sony Xperia 1 VI', brand: 'Sony', category: 'mobiles', price: 1399, discountPrice: 1349, stock: 8, images: [IMG.minimal_phone, IMG.pixel_phone], description: 'Professional creator smartphone with true 85mm-170mm continuous optical telephoto zoom lens and 3.5mm audiophile jack.', specs: { Chipset: 'Snapdragon 8 Gen 3', RAM: '12GB LPDDR5X', Storage: '256GB Expandable up to 1.5TB MicroSD', Display: '6.5" FHD+ LTPO OLED 1-120Hz HDR BRAVIA engine', Audio: 'Full-stage Stereo Speakers, 3.5mm Hi-Res Audio Jack', Battery: '5000 mAh (2-day battery life)' }, rating: 4.6, numReviews: 19 },
  { title: 'Nothing Phone (2) Dark Grey', brand: 'Nothing', category: 'mobiles', price: 599, discountPrice: 549, stock: 40, images: [IMG.minimal_phone, IMG.iphone_titanium], description: 'Iconic transparent rear aesthetics with updated Glyph Interface, Nothing OS 2.5, and dual 50MP Sony sensors.', specs: { Chipset: 'Snapdragon 8+ Gen 1', RAM: '12GB LPDDR5', Storage: '256GB UFS 3.1', Display: '6.7" Flexible LTPO OLED 120Hz', Battery: '4700 mAh (45W Fast Charging)', Interface: 'Custom Glyph LED Matrix notifications' }, rating: 4.7, numReviews: 53 },
  { title: 'Motorola Edge 50 Ultra', brand: 'Motorola', category: 'mobiles', price: 949, discountPrice: 899, stock: 15, images: [IMG.minimal_phone, IMG.samsung_ultra], description: 'Real Nordic Wood back panel design, Pantone-validated camera colors, and 125W TurboPower charging.', specs: { Chipset: 'Snapdragon 8s Gen 3', RAM: '16GB LPDDR5X', Storage: '1TB UFS 4.0', Display: '6.7" Super HD (1220p) pOLED 144Hz', Charging: '125W Wired + 50W Wireless' }, rating: 4.6, numReviews: 22 },
  { title: 'Samsung Galaxy Z Fold 6 5G', brand: 'Samsung', category: 'mobiles', price: 1899, discountPrice: 1799, stock: 10, images: [IMG.samsung_ultra, IMG.gaming_phone], description: 'Ultra-slim dual-screen foldable with Armor Aluminum frame, IP48 water protection, and 7.6-inch Dynamic AMOLED internal canvas.', specs: { Chipset: 'Snapdragon 8 Gen 3 for Galaxy', RAM: '12GB LPDDR5X', Storage: '512GB UFS 4.0', Displays: 'Cover: 6.3" 120Hz | Inner: 7.6" QXGA+ Foldable 120Hz', Hinge: 'Zero-gap Dual Rail Flex Hinge' }, rating: 4.8, numReviews: 41, isFeatured: true },
  { title: 'Samsung Galaxy Z Flip 6', brand: 'Samsung', category: 'mobiles', price: 1099, discountPrice: 999, stock: 22, images: [IMG.samsung_ultra, IMG.minimal_phone], description: 'Compact pocketable clamshell with 3.4-inch Super AMOLED FlexWindow cover display and 50MP dual cameras.', specs: { Chipset: 'Snapdragon 8 Gen 3 for Galaxy', RAM: '12GB', Storage: '256GB', Display: '6.7" FHD+ Foldable 120Hz Dynamic AMOLED', Battery: '4000 mAh with Vapor Chamber cooling' }, rating: 4.7, numReviews: 35 },
  { title: 'Apple iPhone 15', brand: 'Apple', category: 'mobiles', price: 799, discountPrice: 729, stock: 35, images: [IMG.iphone_titanium, IMG.minimal_phone], description: 'Dynamic Island, color-infused back glass, A16 Bionic silicon, and 48MP Main camera with 2x optical-quality zoom.', specs: { Chipset: 'Apple A16 Bionic (4nm)', RAM: '6GB', Storage: '128GB NVMe', Display: '6.1" Super Retina XDR OLED', Connector: 'USB-C Universal Standard' }, rating: 4.8, numReviews: 92 },
  { title: 'Vivo X100 Pro 5G ZEISS Optics', brand: 'Vivo', category: 'mobiles', price: 1049, discountPrice: 989, stock: 14, images: [IMG.gaming_phone, IMG.minimal_phone], description: 'Co-engineered with ZEISS featuring 1-inch Main Sensor, APO Floating Telephoto, and Dimensity 9300 All-Big-Core architecture.', specs: { Chipset: 'MediaTek Dimensity 9300 (4nm)', RAM: '16GB LPDDR5T', Storage: '512GB UFS 4.0', Camera: '50MP 1-inch + 50MP ZEISS APO Telephoto', Battery: '5400 mAh (100W FlashCharge)' }, rating: 4.8, numReviews: 28 },
  { title: 'Realme GT 6 AI Flagship', brand: 'Realme', category: 'mobiles', price: 549, discountPrice: 499, stock: 45, images: [IMG.minimal_phone, IMG.gaming_phone], description: 'Flagship performance with Snapdragon 8s Gen 3, ultra-bright 6000-nit hyper display, and 120W SuperVOOC power.', specs: { Chipset: 'Snapdragon 8s Gen 3', RAM: '12GB', Storage: '256GB', Display: '6.78" 120Hz 8T LTPO, 6000 nits peak', Battery: '5500 mAh Dual-Cell' }, rating: 4.6, numReviews: 31 },
  { title: 'POCO F6 Pro', brand: 'POCO', category: 'mobiles', price: 499, discountPrice: 459, stock: 50, images: [IMG.gaming_phone, IMG.minimal_phone], description: 'High-end gaming performance for value seekers with WQHD+ 120Hz AMOLED and Snapdragon 8 Gen 2.', specs: { Chipset: 'Qualcomm Snapdragon 8 Gen 2', RAM: '12GB LPDDR5X', Storage: '512GB UFS 4.0', Display: '6.67" WQHD+ Flow AMOLED 120Hz', Charging: '120W HyperCharge (0-100% in 19 mins)' }, rating: 4.7, numReviews: 64 },
  { title: 'iQOO 12 Legend Edition', brand: 'iQOO', category: 'mobiles', price: 699, discountPrice: 649, stock: 25, images: [IMG.gaming_phone, IMG.minimal_phone], description: 'BMW M Motorsport design edition with dedicated Q1 Supercomputing gaming chip for frame interpolation.', specs: { Chipset: 'Snapdragon 8 Gen 3 + SuperComputing Q1', RAM: '16GB LPDDR5X', Storage: '512GB UFS 4.0', Display: '6.78" 1.5K AMOLED 144Hz', Battery: '5000 mAh (120W FlashCharge)' }, rating: 4.8, numReviews: 39 },
  { title: 'Google Pixel 8a', brand: 'Google', category: 'mobiles', price: 499, discountPrice: 449, stock: 35, images: [IMG.pixel_phone, IMG.minimal_phone], description: 'Google Tensor G3 flagship processing with 7 years of Pixel Feature Drops, Best Take, and Magic Audio Eraser.', specs: { Chipset: 'Google Tensor G3', RAM: '8GB LPDDR5x', Storage: '128GB UFS 3.1', Display: '6.1" Actua OLED 120Hz', Security: 'Titan M2 Coprocessor, Face & Fingerprint Unlock' }, rating: 4.7, numReviews: 78 },
  { title: 'Nubia RedMagic 9 Pro Gaming Phone', brand: 'Nubia', category: 'mobiles', price: 799, discountPrice: 749, stock: 16, images: [IMG.gaming_phone, IMG.minimal_phone], description: 'True bezel-less under-display camera with active internal 22,000 RPM RGB cooling fan and 6500mAh massive cell.', specs: { Chipset: 'Snapdragon 8 Gen 3 Leading Version', Cooling: 'Built-in 22,000 RPM Turbofan + ICE 13.0 Magic Cooling', Display: '6.8" Flat AMOLED 120Hz Under-Display Selfie', Battery: '6500 mAh (80W Quick Charging)' }, rating: 4.9, numReviews: 44 },

  // ==================== LAPTOPS (18) ====================
  { title: 'Apple MacBook Pro 16" Space Black (M3 Max)', brand: 'Apple', category: 'laptops', price: 3499, discountPrice: 3299, stock: 15, images: [IMG.macbook_spaceblack, IMG.ultrabook], description: 'Monster workstation speed for 3D animators and ML engineers with 16-core CPU, 40-core GPU, and Liquid Retina XDR.', specs: { Processor: 'Apple M3 Max (16-core CPU, 40-core GPU)', Memory: '48GB Unified Memory (300GB/s bandwidth)', Storage: '1TB Superfast PCIe SSD', Display: '16.2" Liquid Retina XDR (3456x2234), 120Hz ProMotion, 1600 nits HDR', Battery: 'Up to 22 hours continuous battery life', Ports: '3x Thunderbolt 4, HDMI 2.1, SDXC slot, MagSafe 3' }, rating: 5.0, numReviews: 110, isFeatured: true },
  { title: 'Apple MacBook Air 15" Midnight (M3)', brand: 'Apple', category: 'laptops', price: 1299, discountPrice: 1199, stock: 30, images: [IMG.macbook_spaceblack, IMG.ultrabook], description: 'Impossibly thin 11.5mm fanless silent aluminum unibody design powered by Apple M3 silicon with dual external monitor support.', specs: { Processor: 'Apple M3 (8-core CPU, 10-core GPU)', Memory: '16GB Unified Memory', Storage: '512GB SSD', Display: '15.3" Liquid Retina LED (2880x1864) 500 nits', Chassis: '11.5mm thin, 3.3 lbs fanless silent operation' }, rating: 4.9, numReviews: 76 },
  { title: 'Dell XPS 16 (2024 Edition)', brand: 'Dell', category: 'laptops', price: 2499, discountPrice: 2299, stock: 12, images: [IMG.dell_xps, IMG.ultrabook], description: 'Minimalist CNC aluminum and Gorilla Glass 3 construction, invisible seamless haptic glass trackpad, and OLED 4K infinity edge.', specs: { Processor: 'Intel Core Ultra 9 185H (16 cores, up to 5.1GHz, Intel AI Boost NPU)', GPU: 'NVIDIA GeForce RTX 4070 Laptop (8GB GDDR6)', RAM: '32GB LPDDR5X 7467MHz Dual Channel', Storage: '1TB M.2 PCIe Gen4 NVMe SSD', Display: '16.3" 4K+ (3840x2400) OLED Touch 120Hz, 100% DCI-P3' }, rating: 4.7, numReviews: 43, isFeatured: true },
  { title: 'ASUS ROG Zephyrus G16 OLED Gaming Laptop', brand: 'ASUS', category: 'laptops', price: 2699, discountPrice: 2499, stock: 14, images: [IMG.gaming_laptop, IMG.dell_xps], description: 'CNC-machined aluminum gaming ultrabook with ROG Nebula 2.5K 240Hz OLED panel and Slash Lighting programmable lid matrix.', specs: { Processor: 'Intel Core Ultra 9 185H', GPU: 'NVIDIA GeForce RTX 4080 (12GB GDDR6, 115W TGP)', RAM: '32GB LPDDR5X-7467MHz', Storage: '2TB PCIe 4.0 NVMe SSD', Display: '16" 2.5K (2560x1600) ROG Nebula OLED 240Hz, 0.2ms', Weight: '1.85 kg ultra-portable gaming form factor' }, rating: 4.9, numReviews: 58, isFeatured: true },
  { title: 'Lenovo Legion Pro 7i Gen 9 (RTX 4090)', brand: 'Lenovo', category: 'laptops', price: 3199, discountPrice: 2999, stock: 8, images: [IMG.gaming_laptop, IMG.dell_xps], description: 'AI-tuned esports battle station with Legion ColdFront Vapor chamber cooling delivering a full unthrottled 175W RTX 4090.', specs: { Processor: 'Intel Core i9-14900HX (24 cores, 32 threads, 5.8GHz Max Turbo)', GPU: 'NVIDIA GeForce RTX 4090 (16GB GDDR6, 175W Max TGP)', RAM: '32GB DDR5-5600MHz (2x 16GB)', Storage: '2TB (2x 1TB) NVMe M.2 SSD Gen4 RAID 0', Display: '16" WQXGA (2560x1600) IPS 240Hz, 500 nits, 100% sRGB' }, rating: 5.0, numReviews: 67, isFeatured: true },
  { title: 'Razer Blade 16 Dual-Mode Mini-LED', brand: 'Razer', category: 'laptops', price: 3799, discountPrice: 3599, stock: 6, images: [IMG.gaming_laptop, IMG.macbook_spaceblack], description: 'World\'s first dual-mode Mini-LED display: switch natively between 4K 120Hz for video editing and FHD+ 240Hz for competitive gaming.', specs: { Processor: 'Intel Core i9-14900HX', GPU: 'NVIDIA GeForce RTX 4090 (16GB GDDR6)', RAM: '64GB DDR5-5600MHz', Storage: '4TB (2x 2TB) PCIe 4.0 SSD', Display: '16" Dual-Mode Mini-LED (UHD+ 120Hz / FHD+ 240Hz)', Chassis: 'T6 CNC Anodized Aluminum with Anti-fingerprint coating' }, rating: 4.8, numReviews: 34 },
  { title: 'Lenovo ThinkPad X1 Carbon Gen 12', brand: 'Lenovo', category: 'laptops', price: 1849, discountPrice: 1699, stock: 20, images: [IMG.ultrabook, IMG.dell_xps], description: 'The executive business benchmark weighing just 1.09 kg with carbon fiber top cover, TrackPoint, and MIL-STD 810H durability.', specs: { Processor: 'Intel Core Ultra 7 155H with Intel vPro', RAM: '32GB LPDDR5X-6400MHz soldered', Storage: '1TB SSD M.2 2280 PCIe Gen4 Performance', Display: '14" 2.8K (2880x1800) OLED 120Hz Anti-Glare, 400 nits', Weight: '1.09 kg (2.42 lbs)' }, rating: 4.8, numReviews: 49 },
  { title: 'ASUS Zenbook Duo Dual-Screen OLED (2024)', brand: 'ASUS', category: 'laptops', price: 1699, discountPrice: 1599, stock: 15, images: [IMG.ultrabook, IMG.dell_xps], description: 'Revolutionary dual 14-inch 3K 120Hz OLED touchscreens with detachable Bluetooth keyboard and built-in kickstand.', specs: { Processor: 'Intel Core Ultra 9 185H', RAM: '32GB LPDDR5X', Storage: '1TB M.2 NVMe PCIe 4.0 SSD', Display: 'Dual 14.0" 3K (2880x1800) OLED 120Hz 0.2ms touchscreens', Productivity: 'Virtual keyboard or physical magnetic snap-on keyboard' }, rating: 4.7, numReviews: 31 },
  { title: 'HP Spectre x360 16 2-in-1', brand: 'HP', category: 'laptops', price: 1799, discountPrice: 1649, stock: 18, images: [IMG.ultrabook, IMG.macbook_spaceblack], description: 'Gem-cut convertible 360-degree aluminum chassis with 9MP AI webcam, IMAX Enhanced display certification, and bundled tilt pen.', specs: { Processor: 'Intel Core Ultra 7 155H', GPU: 'NVIDIA GeForce RTX 4050 Laptop (6GB)', RAM: '32GB LPDDR5X', Storage: '2TB PCIe Gen4 NVMe TLC M.2 SSD', Display: '16" 2.8K (2880x1800) OLED 120Hz Corning Gorilla Glass Touch' }, rating: 4.6, numReviews: 27 },
  { title: 'Acer Predator Helios 18', brand: 'Acer', category: 'laptops', price: 2599, discountPrice: 2399, stock: 10, images: [IMG.gaming_laptop, IMG.dell_xps], description: 'Gigantic 18-inch desktop replacement with MagKey 3.0 mechanical switches and 5th Gen AeroBlade 3D fans with liquid metal thermal paste.', specs: { Processor: 'Intel Core i9-14900HX', GPU: 'NVIDIA GeForce RTX 4080 (12GB GDDR6, 175W)', RAM: '32GB DDR5 5600MHz', Storage: '2TB PCIe Gen4 SSD in RAID 0', Display: '18" WQXGA (2560x1600) Mini LED 250Hz, 1000 nits' }, rating: 4.7, numReviews: 25 },
  { title: 'Framework Laptop 16 Modular Edition', brand: 'Framework', category: 'laptops', price: 1999, discountPrice: 1899, stock: 11, images: [IMG.ultrabook, IMG.dell_xps], description: '100% modular, upgradeable, and repairable laptop with hot-swappable Expansion Bay dedicated GPU module and keyboard spacer systems.', specs: { Processor: 'AMD Ryzen 7 7840HS (8 cores, 16 threads)', GPU: 'Modular AMD Radeon RX 7700S (8GB GDDR6)', RAM: '32GB DDR5-5600 (Upgrade-ready socketed)', Storage: '1TB WD_BLACK SN770 M.2 2280 NVMe', Repairability: '10/10 iFixit score with QR code guides' }, rating: 4.9, numReviews: 42 },
  { title: 'Microsoft Surface Laptop 7 Copilot+ PC', brand: 'Microsoft', category: 'laptops', price: 1399, discountPrice: 1299, stock: 22, images: [IMG.ultrabook, IMG.macbook_spaceblack], description: 'Next-generation Windows on ARM powered by Qualcomm Snapdragon X Elite with 45 TOPS NPU for instant AI Copilot experiences.', specs: { Processor: 'Snapdragon X Elite (12 Cores, 3.8GHz Dual-Core Boost)', NPU: 'Qualcomm Hexagon 45 TOPS', RAM: '16GB LPDDR5X', Storage: '512GB Removable Gen 4 SSD', Display: '15" PixelSense Flow 120Hz Dynamic touchscreen', Battery: 'Up to 20 hours local video playback' }, rating: 4.6, numReviews: 37 },
  { title: 'MSI Titan 18 HX Dragon Edition', brand: 'MSI', category: 'laptops', price: 4999, discountPrice: 4699, stock: 4, images: [IMG.gaming_laptop, IMG.dell_xps], description: 'The most powerful laptop on Earth featuring Cherry MX mechanical keyboard, RGB haptic touchpad, and 270W total system power delivery.', specs: { Processor: 'Intel Core i9-14900HX', GPU: 'NVIDIA GeForce RTX 4090 16GB (175W with Dynamic Boost)', RAM: '128GB DDR5 (4x 32GB)', Storage: '4TB (2x 2TB) PCIe Gen5 + Gen4 SSD', Display: '18" 4K+ (3840x2400) 120Hz Mini LED 1000 nits' }, rating: 5.0, numReviews: 18, isFeatured: true },
  { title: 'ASUS Vivobook Pro 15 OLED', brand: 'ASUS', category: 'laptops', price: 1199, discountPrice: 1049, stock: 28, images: [IMG.ultrabook, IMG.dell_xps], description: 'Creator performance with physical ASUS DialPad integrated into touchpad for instant Photoshop and Premiere Pro brush control.', specs: { Processor: 'Intel Core Ultra 7 155H', GPU: 'NVIDIA GeForce RTX 4060 (8GB)', RAM: '16GB DDR5', Storage: '1TB NVMe SSD', Display: '15.6" 3K (2880x1620) 120Hz OLED 0.2ms Pantone Validated' }, rating: 4.7, numReviews: 51 },
  { title: 'Alienware m18 R2 Gaming Laptop', brand: 'Dell', category: 'laptops', price: 2899, discountPrice: 2699, stock: 9, images: [IMG.gaming_laptop, IMG.dell_xps], description: 'Cryo-tech cooling with quad fans, Element 31 thermal interface material, and full CherryMX ultra-low profile mechanical keyboard.', specs: { Processor: 'Intel Core i9-14900HX', GPU: 'NVIDIA GeForce RTX 4080 12GB', RAM: '32GB Dual-Channel DDR5 5600MHz', Storage: '2TB PCIe NVMe M.2 SSD', Display: '18" QHD+ (2560x1600) 165Hz 3ms ComfortView Plus' }, rating: 4.8, numReviews: 33 },
  { title: 'LG gram Pro 17 Ultra-Lightweight', brand: 'LG', category: 'laptops', price: 1999, discountPrice: 1849, stock: 16, images: [IMG.ultrabook, IMG.macbook_spaceblack], description: 'Astonishing 17-inch workstation that weighs only 1.29 kg (2.86 lbs) with dedicated NVIDIA graphics and magnesium alloy body.', specs: { Processor: 'Intel Core Ultra 7 155H', GPU: 'NVIDIA GeForce RTX 3050 (4GB)', RAM: '32GB LPDDR5X', Storage: '1TB Gen4 NVMe SSD', Display: '17" WQXGA (2560x1600) IPS Anti-Glare 144Hz', Weight: '1.29 kg (2.86 lbs)' }, rating: 4.6, numReviews: 29 },
  { title: 'Gigabyte AORUS 16X (2024)', brand: 'Gigabyte', category: 'laptops', price: 1649, discountPrice: 1499, stock: 21, images: [IMG.gaming_laptop, IMG.dell_xps], description: 'GIGABYTE AI Nexus technology optimizing gaming frame rates and cooling automatically, paired with Pantone color-certified QHD 165Hz.', specs: { Processor: 'Intel Core i7-14650HX', GPU: 'NVIDIA GeForce RTX 4070 (8GB, 140W)', RAM: '16GB DDR5-5600', Storage: '1TB M.2 PCIe 4.0 SSD', Display: '16" 16:10 WQXGA (2560x1600) 165Hz 100% sRGB' }, rating: 4.7, numReviews: 38 },
  { title: 'ASUS TUF Gaming A15', brand: 'ASUS', category: 'laptops', price: 999, discountPrice: 899, stock: 35, images: [IMG.gaming_laptop, IMG.dell_xps], description: 'Military-grade MIL-STD-810H durability with AMD Ryzen 7 processing and full-power RTX 4060 graphics for unbeatable value.', specs: { Processor: 'AMD Ryzen 7 7735HS (8 cores, 16 threads)', GPU: 'NVIDIA GeForce RTX 4060 (8GB GDDR6, 140W)', RAM: '16GB DDR5-4800MHz', Storage: '512GB PCIe 4.0 NVMe SSD', Display: '15.6" FHD 144Hz IPS with G-Sync' }, rating: 4.8, numReviews: 82 },

  // ==================== TABLETS (16) ====================
  { title: 'Apple iPad Pro 13" M4 Ultra-Thin', brand: 'Apple', category: 'tablets', price: 1299, discountPrice: 1229, stock: 25, images: [IMG.ipad_pro, IMG.tablet_stylus], description: 'The thinnest Apple product ever made (5.1mm) with revolutionary Tandem OLED Ultra Retina XDR and the blistering M4 chip.', specs: { Processor: 'Apple M4 Chip (9-core CPU, 10-core GPU with Hardware Ray Tracing)', Display: '13" Tandem OLED Ultra Retina XDR (2752x2064), 1000 nits full screen', Storage: '256GB NVMe', Thickness: '5.1mm ultra-thin aluminum enclosure', Support: 'Apple Pencil Pro with haptic squeeze & barrel roll' }, rating: 5.0, numReviews: 95, isFeatured: true },
  { title: 'Apple iPad Air 11" M2 Chip', brand: 'Apple', category: 'tablets', price: 599, discountPrice: 569, stock: 40, images: [IMG.ipad_pro, IMG.tablet_stylus], description: 'Redesigned iPad Air with landscape 12MP front camera with Center Stage, powered by the incredible M2 chip for pro creativity.', specs: { Processor: 'Apple M2 (8-core CPU, 9-core GPU)', RAM: '8GB Unified Memory', Storage: '128GB', Display: '11" Liquid Retina LED display with True Tone', Audio: 'Landscape stereo speakers with Spatial Audio' }, rating: 4.8, numReviews: 61 },
  { title: 'Samsung Galaxy Tab S9 Ultra (14.6")', brand: 'Samsung', category: 'tablets', price: 1199, discountPrice: 1049, stock: 17, images: [IMG.tablet_stylus, IMG.ipad_pro], description: 'Colossal 14.6-inch Dynamic AMOLED 2X canvas with bundled IP68 water-resistant S Pen and Samsung DeX PC desktop mode.', specs: { Processor: 'Qualcomm Snapdragon 8 Gen 2 for Galaxy', RAM: '12GB', Storage: '512GB (Expandable up to 1TB via MicroSD)', Display: '14.6" Dynamic AMOLED 2X, 120Hz, HDR10+', Protection: 'IP68 water and dust resistance on tablet and S-Pen', Battery: '11,200 mAh (45W Super Fast Charging)' }, rating: 4.9, numReviews: 70, isFeatured: true },
  { title: 'Microsoft Surface Pro 11th Edition 2-in-1', brand: 'Microsoft', category: 'tablets', price: 1499, discountPrice: 1399, stock: 20, images: [IMG.surface_pro, IMG.tablet_stylus], description: 'Copilot+ AI tablet with Snapdragon X Elite silicon, OLED touchscreen, and detachable Flex Keyboard with Pen storage.', specs: { Processor: 'Snapdragon X Elite (12-core)', NPU: '45 TOPS AI processing power', RAM: '16GB LPDDR5x', Storage: '512GB SSD', Display: '13" PixelSense OLED (2880x1920) 120Hz HDR', OS: 'Windows 11 Home AI Optimized' }, rating: 4.7, numReviews: 39 },
  { title: 'Apple iPad mini (6th Gen)', brand: 'Apple', category: 'tablets', price: 499, discountPrice: 449, stock: 35, images: [IMG.ipad_pro, IMG.tablet_stylus], description: 'Ultra-portable 8.3-inch all-screen design with A15 Bionic, USB-C, and Apple Pencil 2 magnetic wireless charging support.', specs: { Processor: 'A15 Bionic chip with 64-bit architecture', Storage: '64GB', Display: '8.3" Liquid Retina with P3 wide color and True Tone', Weight: '293 grams (0.65 lb)' }, rating: 4.9, numReviews: 83 },
  { title: 'OnePlus Pad 2 (Snapdragon 8 Gen 3)', brand: 'OnePlus', category: 'tablets', price: 549, discountPrice: 499, stock: 26, images: [IMG.tablet_stylus, IMG.ipad_pro], description: 'Industry-first 7:5 aspect ratio ReadFit display powered by flagship Snapdragon 8 Gen 3 with 6-speaker spatial audio system.', specs: { Processor: 'Snapdragon 8 Gen 3', RAM: '12GB LPDDR5X', Storage: '256GB UFS 3.1', Display: '12.1" 3K (3000x2120) 144Hz 7:5 ReadFit panel', Battery: '9510 mAh (67W SUPERVOOC charging)' }, rating: 4.8, numReviews: 28 },
  { title: 'Xiaomi Pad 6S Pro 12.4', brand: 'Xiaomi', category: 'tablets', price: 649, discountPrice: 599, stock: 22, images: [IMG.tablet_stylus, IMG.ipad_pro], description: 'Productivity tablet powerhouse with 144Hz 3:2 crystal display, Xiaomi HyperOS workstation mode, and 120W HyperCharge.', specs: { Processor: 'Snapdragon 8 Gen 2 (4nm)', RAM: '8GB', Storage: '256GB', Display: '12.4" 3K 144Hz 3:2 Aspect Ratio, 900 nits', Charging: '120W wired (0-100% in 35 mins)' }, rating: 4.7, numReviews: 32 },
  { title: 'Samsung Galaxy Tab S9 FE+', brand: 'Samsung', category: 'tablets', price: 599, discountPrice: 529, stock: 30, images: [IMG.tablet_stylus, IMG.ipad_pro], description: 'Water-resistant big screen tablet with included S Pen, dual rear cameras, and long-lasting 10,090mAh battery.', specs: { Processor: 'Exynos 1380 (5nm)', RAM: '8GB', Storage: '128GB (MicroSD up to 1TB)', Display: '12.4" WQXGA 90Hz Vision Booster', Durability: 'IP68 Water & Dust Resistant' }, rating: 4.6, numReviews: 44 },
  { title: 'Lenovo Tab P12 Pro', brand: 'Lenovo', category: 'tablets', price: 699, discountPrice: 619, stock: 19, images: [IMG.tablet_stylus, IMG.ipad_pro], description: 'Entertainment centerpiece with 12.6-inch 2K AMOLED, quad JBL speakers with Dolby Atmos, and Precision Pen 3 included.', specs: { Processor: 'Snapdragon 870', RAM: '8GB LPDDR5', Storage: '256GB UFS 3.1', Display: '12.6" 2K (2560x1600) AMOLED 120Hz HDR10+', Speakers: '4x JBL speakers with Dolby Atmos' }, rating: 4.5, numReviews: 24 },
  { title: 'reMarkable 2 Paper Tablet', brand: 'reMarkable', category: 'tablets', price: 399, discountPrice: 379, stock: 28, images: [IMG.tablet_stylus, IMG.surface_pro], description: 'The world\'s slimmest digital paper tablet (4.7mm) engineered strictly for focused note-taking, reading, and sketching with zero distractions.', specs: { Display: '10.3" monochrome Canvas digital paper (226 DPI)', Surface: 'Friction-textured surface replicating actual paper', Battery: 'Up to 2 weeks battery life per charge', Thickness: '4.7 mm' }, rating: 4.8, numReviews: 69 },
  { title: 'Boox Note Air 3 C Color E-Ink', brand: 'Onyx Boox', category: 'tablets', price: 499, discountPrice: 469, stock: 15, images: [IMG.tablet_stylus, IMG.surface_pro], description: 'Kaleido 3 color ePaper Android tablet with paper-like writing feel, front light, and Google Play Store access.', specs: { Display: '10.3" Kaleido 3 (4,096 colors) Carta 1200 glass screen', OS: 'Android 12 open ecosystem', RAM: '4GB LPDDR4X', Storage: '64GB with MicroSD expansion' }, rating: 4.6, numReviews: 21 },
  { title: 'Apple iPad 10th Gen (Blue)', brand: 'Apple', category: 'tablets', price: 349, discountPrice: 319, stock: 50, images: [IMG.ipad_pro, IMG.tablet_stylus], description: 'All-screen 10.9-inch Liquid Retina display with A14 Bionic, USB-C, Touch ID top button, and landscape front camera.', specs: { Processor: 'Apple A14 Bionic', Storage: '64GB', Display: '10.9" Liquid Retina IPS (2360x1640)', Colors: 'Blue, Pink, Yellow, Silver' }, rating: 4.8, numReviews: 120 },
  { title: 'Amazon Fire Max 11', brand: 'Amazon', category: 'tablets', price: 229, discountPrice: 189, stock: 60, images: [IMG.tablet_stylus, IMG.ipad_pro], description: 'Vivid 11-inch 2.4 million pixel display in a slim aluminum casing with octa-core speed and 14-hour battery.', specs: { Processor: 'Octa-core 2.2GHz MediaTek MT8188J', RAM: '4GB', Storage: '64GB (Expandable to 1TB)', Display: '11" 2000x1200 resolution with low blue light cert' }, rating: 4.4, numReviews: 88 },
  { title: 'Lenovo Yoga Tab 11 with Smart Stand', brand: 'Lenovo', category: 'tablets', price: 319, discountPrice: 279, stock: 25, images: [IMG.surface_pro, IMG.tablet_stylus], description: 'Built-in stainless steel kickstand lets you hang, stand, or tilt the tablet, accompanied by quad JBL speakers.', specs: { Processor: 'MediaTek Helio G90T', RAM: '4GB', Storage: '128GB', Display: '11" 2K (2000x1200) Dolby Vision IPS', Design: 'Integrated stainless steel multi-angle hanger/stand' }, rating: 4.5, numReviews: 33 },
  { title: 'Huawei MatePad Pro 13.2 OLED', brand: 'Huawei', category: 'tablets', price: 899, discountPrice: 849, stock: 12, images: [IMG.ipad_pro, IMG.tablet_stylus], description: 'Flexible OLED borderless display weighing only 580g with NearLink low-latency M-Pencil 3rd generation stylus technology.', specs: { Processor: 'Kirin 9000S', RAM: '12GB', Storage: '256GB', Display: '13.2" Flexible OLED, 2.8K 144Hz, 94% screen-to-body ratio', Weight: '580g (1.28 lbs)' }, rating: 4.7, numReviews: 19 },
  { title: 'Wacom Cintiq Pro 17 Creative Display', brand: 'Wacom', category: 'tablets', price: 2499, discountPrice: 2399, stock: 8, images: [IMG.tablet_stylus, IMG.surface_pro], description: 'Reference-grade interactive pen display for professional digital artists and VFX studios with 4K 120Hz 99% DCI-P3 color accuracy.', specs: { Display: '17.3" 4K (3840x2160) 120Hz IPS with zero parallax', Color: '99% DCI-P3, 88% Adobe RGB, Pantone Validated', Pen: 'Wacom Pro Pen 3 with 8,192 pressure levels and custom grips', Connectivity: 'USB-C (DP Alt mode), HDMI 2.1, Mini DisplayPort' }, rating: 4.9, numReviews: 27 },

  // ==================== AUDIO (18) ====================
  { title: 'Sony WH-1000XM5 Noise-Canceling Headphones', brand: 'Sony', category: 'audio', price: 399, discountPrice: 348, stock: 40, images: [IMG.sony_anc, IMG.airpods_max], description: 'Industry-leading noise cancellation engineered with 8 microphones and dual Auto NC Optimizer processors, with LDAC Hi-Res Audio.', specs: { Driver: '30mm carbon-fiber composite driver unit', ANC: 'Dual Processor V1 + HD Noise Canceling QN1', Codecs: 'LDAC, AAC, SBC (Hi-Res Audio Wireless)', Battery: '30 hours with ANC on (3 mins charge = 3 hours playback)', Weight: '250 grams lightweight silent design' }, rating: 4.9, numReviews: 180, isFeatured: true },
  { title: 'Apple AirPods Max (USB-C Space Gray)', brand: 'Apple', category: 'audio', price: 549, discountPrice: 499, stock: 25, images: [IMG.airpods_max, IMG.sony_anc], description: 'Computational audio with Apple H1 chip in each ear cup, custom acoustic driver, knit-mesh canopy, and anodized aluminum cups.', specs: { Driver: '40mm Apple-designed dynamic driver with dual neodymium motor', Chips: 'Apple H1 headphone chip (10 audio cores per ear cup)', Features: 'Personalized Spatial Audio with dynamic head tracking', Port: 'Lossless Audio via USB-C wired or Bluetooth 5.0', Battery: '20 hours listening time with ANC enabled' }, rating: 4.8, numReviews: 140, isFeatured: true },
  { title: 'Bose QuietComfort Ultra Wireless Headphones', brand: 'Bose', category: 'audio', price: 429, discountPrice: 379, stock: 30, images: [IMG.sony_anc, IMG.airpods_max], description: 'Breakthrough spatial Bose Immersive Audio with world-class noise cancellation and CustomTune sound tailored to your ear canal shape.', specs: { Audio: 'Bose Immersive Audio with spatial sound virtualization', ANC: 'CustomTune ear canal measuring acoustic calibration', Microphones: 'Advanced microphone array for crystal clear phone calls', Battery: '24 hours standard / 18 hours with Immersive Audio' }, rating: 4.8, numReviews: 95 },
  { title: 'Sennheiser Momentum 4 Wireless', brand: 'Sennheiser', category: 'audio', price: 379, discountPrice: 299, stock: 28, images: [IMG.sony_anc, IMG.audiophile_openback], description: 'Audiophile-inspired 42mm transducer system delivering signature Sennheiser musicality with massive 60-hour battery life.', specs: { Driver: '42mm audiophile-inspired dynamic transducer', Battery: 'Incredible 60 hours battery life with ANC on', Codecs: 'aptX Adaptive, aptX, AAC, SBC', Comfort: 'Lightweight fold-flat design with padded headband' }, rating: 4.8, numReviews: 72 },
  { title: 'Beyerdynamic DT 990 PRO Studio Headphones (250 Ohm)', brand: 'Beyerdynamic', category: 'audio', price: 169, discountPrice: 149, stock: 45, images: [IMG.audiophile_openback, IMG.sony_anc], description: 'Open-back diffuse-field studio reference headphones handmade in Germany, revered by music producers and audio engineers globally.', specs: { Type: 'Open-back dynamic studio reference', Impedance: '250 Ohms (Requires dedicated DAC/Amp)', Frequency: '5 - 35,000 Hz', EarPads: 'Replaceable soft circumaural velour ear pads', Origin: 'Handcrafted in Germany' }, rating: 4.9, numReviews: 215 },
  { title: 'Sony WF-1000XM5 True Wireless Earbuds', brand: 'Sony', category: 'audio', price: 299, discountPrice: 248, stock: 50, images: [IMG.tws_earbuds, IMG.sony_anc], description: 'Dynamic Driver X delivers wide frequencies with dual feedback microphones and bone-conduction voice sensors.', specs: { Driver: 'Dynamic Driver X (8.4mm)', ANC: 'Integrated Processor V2 + HD Noise Canceling QN2e', Codecs: 'LDAC Hi-Res Audio Wireless, LC3, AAC, SBC', WaterResistance: 'IPX4 splash and sweat proof', Battery: '8 hrs earbuds + 16 hrs wireless Qi charging case' }, rating: 4.7, numReviews: 112 },
  { title: 'Apple AirPods Pro (2nd Generation with USB-C)', brand: 'Apple', category: 'audio', price: 249, discountPrice: 199, stock: 65, images: [IMG.tws_earbuds, IMG.airpods_max], description: 'Up to 2x more Active Noise Cancellation, Adaptive Audio, Transparency mode, and Conversation Awareness powered by the H2 chip.', specs: { Chip: 'Apple H2 chip, Apple U1/U2 chip in MagSafe case', Audio: 'Adaptive Audio with Personalized Volume and Spatial Audio', Case: 'MagSafe USB-C case with built-in speaker and lanyard loop', Rating: 'IP54 dust, sweat, and water resistance' }, rating: 4.9, numReviews: 320, isFeatured: true },
  { title: 'Sennheiser HD 660S2 Audiophile Headphones', brand: 'Sennheiser', category: 'audio', price: 599, discountPrice: 499, stock: 15, images: [IMG.audiophile_openback, IMG.sony_anc], description: 'Intimate, warm acoustic precision with revised 300-ohm aluminum voice coil and ventilated magnetic system.', specs: { Acoustics: 'Open-back dynamic transducer', Impedance: '300 Ohms', THD: '< 0.05% (1 kHz, 100 dB SPL)', Cable: 'Detachable OFC copper cables (6.3mm and 4.4mm balanced)' }, rating: 4.9, numReviews: 48 },
  { title: 'Bowers & Wilkins Px8 Flagship Wireless', brand: 'Bowers & Wilkins', category: 'audio', price: 699, discountPrice: 629, stock: 12, images: [IMG.sony_anc, IMG.airpods_max], description: 'Cast aluminum arms, Nappa leather trim, and angled 40mm Carbon Cone drive units derived from high-end 700 Series loudspeakers.', specs: { Driver: 'Angled 40mm full-range carbon cone drivers', Materials: 'Die-cast aluminum arms and fine Nappa leather', DAC: 'High-resolution 24-bit DSP with aptX Lossless', Battery: '30 hours battery life' }, rating: 4.8, numReviews: 31 },
  { title: 'Audio-Technica ATH-M50x Professional Monitor', brand: 'Audio-Technica', category: 'audio', price: 169, discountPrice: 149, stock: 60, images: [IMG.audiophile_openback, IMG.sony_anc], description: 'The industry-standard tracking and studio mixing monitor headphones with 45mm large-aperture drivers and 90-degree swiveling earcups.', specs: { Driver: '45mm neodymium magnet with copper-clad aluminum wire', Frequency: '15 - 28,000 Hz', Cables: '3 detachable cables included (coiled and straight)', Design: 'Collapsible for space-saving portability' }, rating: 4.9, numReviews: 410 },
  { title: 'Shure SM7B Cardioid Studio Vocal Microphone', brand: 'Shure', category: 'audio', price: 399, discountPrice: 389, stock: 35, images: [IMG.stream_setup, IMG.sony_anc], description: 'The world standard vocal and broadcast microphone for podcasters, streamers, and recording studios with electromagnetic shielding.', specs: { Type: 'Dynamic (moving coil)', PolarPattern: 'Cardioid flat, wide-range frequency response', Shielding: 'Internal air suspension shock isolation and humbucking filter', Connector: '3-pin XLR professional audio interface connection' }, rating: 5.0, numReviews: 275 },
  { title: 'SteelSeries Arctis Nova Pro Wireless Gaming Headset', brand: 'SteelSeries', category: 'audio', price: 349, discountPrice: 319, stock: 25, images: [IMG.sony_anc, IMG.gaming_mouse], description: 'Esports audio with Nova Pro Acoustic System, active noise cancellation, and hot-swap dual-battery Infinity Power system.', specs: { Audio: 'High-Res Capable Premium Neodymium Magnetic Drivers', BaseStation: 'Dual USB Multi-System Connect Base Station with OLED screen', Battery: 'Hot-swappable dual battery system for non-stop gaming', Mic: 'ClearCast Gen 2 fully retractable bidirectional AI noise-canceling mic' }, rating: 4.8, numReviews: 88, isFeatured: true },
  { title: 'Focal Bathys Hi-Fi ANC Wireless Headphones', brand: 'Focal', category: 'audio', price: 699, discountPrice: 629, stock: 10, images: [IMG.sony_anc, IMG.audiophile_openback], description: "Made in France with Aluminum/Magnesium 'M'-shaped dome drivers and built-in USB-DAC mode supporting 24-bit/192kHz audio.", specs: { Drivers: "40mm Aluminum/Magnesium 'M'-shaped dome made in France", DACMode: 'Integrated USB-DAC mode delivering up to 24-bit / 192kHz', ANC: 'Silent, Soft, and Transparency active noise isolation modes' }, rating: 4.9, numReviews: 24 },
  { title: 'JBL Flip 6 Portable Waterproof Bluetooth Speaker', brand: 'JBL', category: 'audio', price: 129, discountPrice: 99, stock: 75, images: [IMG.tws_earbuds, IMG.sony_anc], description: '2-way speaker system delivering powerful, crystal clear JBL Original Pro Sound with IP67 waterproof and dustproof protection.', specs: { Output: '20W RMS woofer + 10W RMS tweeter', Protection: 'IP67 Waterproof and Dustproof', Battery: 'Up to 12 hours playtime on single charge', Feature: 'PartyBoost linking multiple compatible speakers' }, rating: 4.7, numReviews: 190 },
  { title: 'Sonos Move 2 Smart Speaker with Wi-Fi & Bluetooth', brand: 'Sonos', category: 'audio', price: 449, discountPrice: 419, stock: 18, images: [IMG.tws_earbuds, IMG.sony_anc], description: 'Dual-tweeter acoustic architecture pumping out spacious stereo sound indoors or outdoors with 24 hours of portable battery life.', specs: { Acoustics: 'Dual angled tweeters + precision-tuned midwoofer', Connectivity: 'Wi-Fi 6, Bluetooth 5.0, Apple AirPlay 2', Trueplay: 'Automatic tuning continuously adjusts acoustics to surroundings', Battery: '24 hours continuous battery life with wireless charging base' }, rating: 4.8, numReviews: 53 },
  { title: 'Marshall Stanmore III Bluetooth Speaker', brand: 'Marshall', category: 'audio', price: 379, discountPrice: 349, stock: 22, images: [IMG.audiophile_openback, IMG.sony_anc], description: 'Iconic vintage rock-and-roll styling with a wider stereo soundstage and dynamic loudness that adjusts tonal balance at every volume.', specs: { Amplifiers: 'One 50W Class D for woofer + Two 15W Class D for tweeters', Inputs: 'Bluetooth 5.2, 3.5mm Aux input, RCA stereo inputs', Controls: 'Brass analog control knobs for bass, treble, and volume' }, rating: 4.8, numReviews: 64 },
  { title: 'Nothing Ear (2024 Release)', brand: 'Nothing', category: 'audio', price: 149, discountPrice: 129, stock: 45, images: [IMG.tws_earbuds, IMG.sony_anc], description: 'Ceramic driver diaphragm for ultra-crisp highs, 45dB Smart ANC, LHDC 5.0 / LDAC support, and ChatGPT voice assistant integration.', specs: { Driver: 'Custom 11mm ceramic driver', Codecs: 'LDAC and LHDC 5.0 certified for 24-bit/192kHz streaming', ANC: 'Smart Active Noise Cancellation up to 45 dB with Leakage Detection', Integration: 'Voice-pinch ChatGPT access on Nothing phones' }, rating: 4.6, numReviews: 57 },
  { title: 'Focusrite Scarlett 2i2 4th Gen USB Audio Interface', brand: 'Focusrite', category: 'audio', price: 199, discountPrice: 179, stock: 35, images: [IMG.stream_setup, IMG.audiophile_openback], description: 'Studio converters with 120dB dynamic range, remote-controlled 4th Gen preamps, Auto Gain, Clip Safe, and re-engineered Air Mode.', specs: { Preamps: '2 ultra-low-noise 4th-generation mic preamps (69dB gain range)', Converters: '24-bit / 192kHz AD/DA studio-grade converters', Features: 'Auto Gain calibration, Clip Safe protection, Harmonic Air Mode' }, rating: 4.9, numReviews: 130 },

  // ==================== PC COMPONENTS (18) ====================
  { title: 'ASUS ROG Matrix GeForce RTX 4090 Platinum 24GB', brand: 'ASUS', category: 'pc-components', price: 3199, discountPrice: 2999, stock: 5, images: [IMG.rtx_gpu, IMG.motherboard_rig], description: 'The fastest consumer graphics card in history featuring liquid metal TIM on the GPU die and custom 360mm radiator loop.', specs: { CUDA: '16,384 CUDA Cores', BoostClock: '2700 MHz (OC Mode)', VRAM: '24GB GDDR6X (384-bit memory bus)', Cooling: 'Liquid Metal Compound + Integrated 360mm AIO Radiator', Power: 'Native 16-pin 12VHPWR connector with power-sensing LEDs' }, rating: 5.0, numReviews: 41, isFeatured: true },
  { title: 'NVIDIA GeForce RTX 4080 Super Founders Edition', brand: 'NVIDIA', category: 'pc-components', price: 999, discountPrice: 969, stock: 14, images: [IMG.rtx_gpu, IMG.motherboard_rig], description: 'Dual-axial flow-through cooling masterpiece delivering AI DLSS 3.5 Frame Generation and 4K max ray-traced rendering.', specs: { CUDA: '10,240 Cores', VRAM: '16GB GDDR6X (23 Gbps speed)', TGP: '320W Total Graphics Power', Outputs: '3x DisplayPort 1.4a, 1x HDMI 2.1a' }, rating: 4.9, numReviews: 89 },
  { title: 'AMD Ryzen 9 7950X3D 16-Core Processor', brand: 'AMD', category: 'pc-components', price: 649, discountPrice: 569, stock: 22, images: [IMG.motherboard_rig, IMG.ram_liquid_cooler], description: 'The world\'s fastest gaming processor with 144MB of 3D V-Cache technology built on cutting-edge 5nm Zen 4 architecture.', specs: { CoresThreads: '16 Cores, 32 Threads', MaxBoostClock: 'Up to 5.7 GHz', Cache: '144MB (L2+L3 3D V-Cache)', Socket: 'AM5 (PCIe 5.0, DDR5 Only)', TDP: '120W power-efficient flagship' }, rating: 4.9, numReviews: 110, isFeatured: true },
  { title: 'Intel Core i9-14900KS Special Edition CPU', brand: 'Intel', category: 'pc-components', price: 689, discountPrice: 659, stock: 10, images: [IMG.motherboard_rig, IMG.ram_liquid_cooler], description: 'World record out-of-the-box 6.2 GHz max turbo frequency desktop processor for extreme overclockers and high-FPS enthusiasts.', specs: { CoresThreads: '24 Cores (8 P-cores + 16 E-cores), 32 Threads', MaxTurbo: '6.2 GHz with Intel Thermal Velocity Boost', Socket: 'LGA1700 (Intel 600/700 Series Motherboards)', BasePower: '150W Base (253W+ Extreme Power Delivery Profile)' }, rating: 4.7, numReviews: 46 },
  { title: 'ASUS ROG Maximus Z790 Dark Hero Motherboard', brand: 'ASUS', category: 'pc-components', price: 699, discountPrice: 649, stock: 15, images: [IMG.motherboard_rig, IMG.ram_liquid_cooler], description: 'LGA 1700 motherboard with 20+1+2 power stages, on-board Wi-Fi 7, dual Thunderbolt 4 ports, and PCIe 5.0 M.2 slot.', specs: { VRM: '20+1+2 teamed power stages (90A rating)', Memory: '4x DDR5 DIMMs, up to 8000+ MHz (OC)', Networking: 'Wi-Fi 7 (802.11be) + Intel 2.5 Gb Ethernet', Storage: '5x M.2 slots (including 1x PCIe 5.0 x4)' }, rating: 4.8, numReviews: 38 },
  { title: 'Corsair Dominator Titanium RGB DDR5 64GB (2x32GB) 6000MHz', brand: 'Corsair', category: 'pc-components', price: 319, discountPrice: 289, stock: 25, images: [IMG.ram_liquid_cooler, IMG.motherboard_rig], description: 'Precision forged aluminum memory with customizable swappable top bars, patented DHX cooling, and 11 addressable RGB LEDs.', specs: { Capacity: '64GB (2x 32GB Kit)', Speed: 'DDR5 6000 MT/s (CL30-36-36-76)', Profiles: 'Intel XMP 3.0 & AMD EXPO certified', Lighting: '11 individual CAPELLIX RGB LEDs per module' }, rating: 4.9, numReviews: 63 },
  { title: 'Samsung 990 PRO 4TB NVMe M.2 SSD with Heatsink', brand: 'Samsung', category: 'pc-components', price: 379, discountPrice: 329, stock: 35, images: [IMG.nvme_ssd, IMG.motherboard_rig], description: 'Peak PCIe 4.0 read speeds up to 7,450 MB/s with smart thermal control heatsink, ideal for PlayStation 5 and high-end rigs.', specs: { SequentialRead: 'Up to 7,450 MB/s', SequentialWrite: 'Up to 6,900 MB/s', Controller: 'Samsung Pascal In-House Controller', Heatsink: 'Integrated slim heatsink with RGB LED indicator', Endurance: '2,400 TBW (Terabytes Written)' }, rating: 5.0, numReviews: 184, isFeatured: true },
  { title: 'Crucial T700 2TB PCIe Gen5 NVMe SSD', brand: 'Crucial', category: 'pc-components', price: 299, discountPrice: 269, stock: 18, images: [IMG.nvme_ssd, IMG.motherboard_rig], description: 'Next-gen PCIe 5.0 performance delivering sequential speeds up to 12,400 MB/s with premium aluminum and copper passive heatsink.', specs: { Interface: 'PCIe Gen 5.0 x4, NVMe 2.0', SequentialRead: '12,400 MB/s', SequentialWrite: '11,800 MB/s', NAND: 'Micron 232-layer 3D TLC NAND' }, rating: 4.8, numReviews: 52 },
  { title: 'NZXT Kraken Elite 360 RGB AIO Liquid CPU Cooler', brand: 'NZXT', category: 'pc-components', price: 299, discountPrice: 279, stock: 20, images: [IMG.ram_liquid_cooler, IMG.motherboard_rig], description: 'High-performance Asetek pump with a brilliant 2.36-inch wide-angle 640x640 LCD screen for displaying real-time system stats or custom GIFs.', specs: { Display: '2.36" diameter 60Hz LCD, 640x640 resolution, 690 cd/m²', Radiator: '360mm Aluminum radiator (3x 120mm F120 RGB Core Fans)', Pump: 'Asetek 7th Gen variable speed 800 - 2,800 RPM', Tubing: '400mm ultra-low evaporation rubber with braided nylon sleeve' }, rating: 4.9, numReviews: 92 },
  { title: 'Lian Li O11 Dynamic EVO RGB PC Case', brand: 'Lian Li', category: 'pc-components', price: 169, discountPrice: 159, stock: 30, images: [IMG.motherboard_rig, IMG.ram_liquid_cooler], description: 'Dual-chamber panoramic chassis with removable front pillar for seamless glass view, dual ARGB lighting strips, and reversible orientation.', specs: { Dimensions: '(D) 478mm x (W) 290mm x (H) 471mm', Motherboard: 'E-ATX (under 280mm) / ATX / Micro-ATX / Mini-ITX', RadiatorSupport: 'Top 360mm, Side 360mm, Bottom 360mm simultaneously', Materials: '4mm Tempered Glass, 1.5mm Brushed Aluminum' }, rating: 4.9, numReviews: 140 },
  { title: 'Corsair RM1000x Shift Fully Modular ATX 3.0 Power Supply', brand: 'Corsair', category: 'pc-components', price: 209, discountPrice: 189, stock: 24, images: [IMG.motherboard_rig, IMG.rtx_gpu], description: 'Revolutionary side-mounted modular cable interface makes clean cable management in tight chassis effortless. 80 PLUS Gold certified.', specs: { Wattage: '1000 Watts Continuous Output', Standard: 'ATX 3.0 & PCIe 5.0 compliant with native 12VHPWR cable', Efficiency: '80 PLUS Gold Certified', Fan: '140mm fluid dynamic bearing with Zero RPM silent mode' }, rating: 4.8, numReviews: 78 },
  { title: 'Noctua NH-D15 chromax.black Dual-Tower CPU Cooler', brand: 'Noctua', category: 'pc-components', price: 119, discountPrice: 109, stock: 40, images: [IMG.ram_liquid_cooler, IMG.motherboard_rig], description: 'The legendary king of quiet air cooling in an all-black stealth finish with dual NF-A15 140mm PWM fans and SecuFirm2 mounting.', specs: { Design: 'Dual-tower 6-heatpipe heatsink', Fans: '2x NF-A15 HS-PWM chromax.black 140mm fans', Noise: 'Max 24.6 dB(A) with low-noise adapters', ThermalPaste: 'Includes high-end NT-H1 thermal compound' }, rating: 5.0, numReviews: 310 },
  { title: 'MSI MAG CoreLiquid E360 AIO Liquid Cooler', brand: 'MSI', category: 'pc-components', price: 139, discountPrice: 119, stock: 22, images: [IMG.ram_liquid_cooler, IMG.motherboard_rig], description: 'Enlarged copper base with optimized micro-channels and 270-degree rotatable circular RGB blockhead.', specs: { Radiator: '360mm Aluminum', Fans: '3x 120mm ARGB Fans (Fluid Dynamic Bearing)', Compatibility: 'Intel LGA 1700/1200/115x, AMD AM5/AM4' }, rating: 4.6, numReviews: 45 },
  { title: 'G.Skill Trident Z5 RGB 32GB (2x16GB) DDR5 7200MHz', brand: 'G.Skill', category: 'pc-components', price: 189, discountPrice: 169, stock: 28, images: [IMG.ram_liquid_cooler, IMG.motherboard_rig], description: 'Hyper-speed DDR5 memory engineered with hand-screened ICs and sleek dual-texture aluminum heatspreaders.', specs: { Speed: '7200 MT/s (CL34-45-45-115)', Capacity: '32GB (2x 16GB)', Profile: 'Intel XMP 3.0 Ready' }, rating: 4.8, numReviews: 61 },
  { title: 'Seasonic Prime TX-1300 ATX 3.0 Titanium PSU', brand: 'Seasonic', category: 'pc-components', price: 499, discountPrice: 459, stock: 8, images: [IMG.motherboard_rig, IMG.rtx_gpu], description: 'Ultra-high efficiency 80 PLUS Titanium power supply backed by an industry-leading 12-year manufacturer warranty.', specs: { Wattage: '1300 Watts', Certification: '80 PLUS Titanium (94% efficiency at 50% load)', Regulation: 'Micro Tolerance Load Regulation (< 0.5%)', Warranty: '12-Year Global Warranty' }, rating: 5.0, numReviews: 32 },
  { title: 'Western Digital WD_BLACK SN850X 2TB NVMe SSD', brand: 'Western Digital', category: 'pc-components', price: 179, discountPrice: 159, stock: 45, images: [IMG.nvme_ssd, IMG.motherboard_rig], description: 'Crush load times with Game Mode 2.0 predictive loading and read speeds reaching up to 7,300 MB/s.', specs: { Speed: 'Up to 7,300 MB/s Read, 6,600 MB/s Write', FormFactor: 'M.2 2280 PCIe Gen4 x4', Feature: 'WD_BLACK Dashboard Game Mode 2.0' }, rating: 4.9, numReviews: 165 },
  { title: 'Corsair iCUE LINK QX120 RGB 120mm PWM Fans (3-Pack)', brand: 'Corsair', category: 'pc-components', price: 139, discountPrice: 124, stock: 35, images: [IMG.ram_liquid_cooler, IMG.motherboard_rig], description: "Smart single-cable ecosystem connecting fans together sequentially without a rat's nest of wires. Features 34 RGB LEDs per fan.", specs: { System: 'iCUE LINK unified cable ecosystem', Lighting: '34 RGB LEDs across two distinct light loops', StrobeEffect: 'Exclusive Time Warp zero-RPM optical illusion mode' }, rating: 4.7, numReviews: 54 },
  { title: 'Thermal Grizzly Kryonaut Extreme Thermal Paste (2g)', brand: 'Thermal Grizzly', category: 'pc-components', price: 24, discountPrice: 19, stock: 120, images: [IMG.motherboard_rig, IMG.ram_liquid_cooler], description: 'Engineered for extreme sub-zero overclocking and ultra-high heat dissipation with nano-aluminum oxide particles.', specs: { ThermalConductivity: '14.2 W/m*K', Viscosity: '130-180 Pas', OperatingTemp: '-250 °C to +350 °C', Electrical: 'Non-conductive, safe on all silicon dies' }, rating: 4.9, numReviews: 350 },

  // ==================== GAMING GEAR (17) ====================
  { title: 'ASUS ROG Swift OLED PG32UCDM 32" 4K 240Hz Monitor', brand: 'ASUS', category: 'gaming-gear', price: 1299, discountPrice: 1249, stock: 10, images: [IMG.curved_monitor, IMG.stream_setup], description: 'Third-generation 32-inch 4K QD-OLED panel with 240Hz refresh rate, 0.03ms response time, custom graphene heatsink, and Dolby Vision.', specs: { Panel: '31.5" Quantum Dot OLED (QD-OLED) Anti-Reflection', Resolution: '4K UHD (3840 x 2160)', RefreshRate: '240Hz with 0.03ms (GTG) response time', Brightness: '1000 nits peak (3% window), 99% DCI-P3 coverage', Ports: 'DisplayPort 1.4 (DSC), HDMI 2.1, USB-C (90W Power Delivery)' }, rating: 5.0, numReviews: 74, isFeatured: true },
  { title: 'Samsung Odyssey OLED G9 49" Curved UltraWide (240Hz)', brand: 'Samsung', category: 'gaming-gear', price: 1599, discountPrice: 1299, stock: 8, images: [IMG.curved_monitor, IMG.stream_setup], description: 'Enormous 32:9 dual QHD curved OLED display powered by Neo Quantum Processor Pro for instant frame analysis and infinite contrast.', specs: { ScreenSize: '49" Curved 1800R Ultra-wide 32:9 Dual QHD (5120x1440)', Panel: 'OLED with 0.03ms response time & 240Hz refresh rate', SmartPlatform: 'Samsung Gaming Hub with cloud streaming built-in', Chassis: 'Ultra-slim metal frame with CoreSync ambient rear lighting' }, rating: 4.8, numReviews: 82, isFeatured: true },
  { title: 'Logitech G PRO X SUPERLIGHT 2 Wireless Gaming Mouse', brand: 'Logitech G', category: 'gaming-gear', price: 159, discountPrice: 144, stock: 50, images: [IMG.gaming_mouse, IMG.mechanical_keyboard], description: 'The preferred weapon of world-champion esports pros weighing just 60 grams with LIGHTFORCE hybrid optical-mechanical switches.', specs: { Weight: '60 grams featherlight symmetrical design', Sensor: 'HERO 2 (Up to 32,000 DPI, 500+ IPS tracking)', PollingRate: 'True 4000Hz / 8000Hz polling capability via USB-C', Battery: '95 hours continuous motion battery life' }, rating: 4.9, numReviews: 240, isFeatured: true },
  { title: 'Wooting 60HE+ Analog Hall Effect Keyboard', brand: 'Wooting', category: 'gaming-gear', price: 199, discountPrice: 189, stock: 15, images: [IMG.mechanical_keyboard, IMG.gaming_mouse], description: 'Magnetic Lekker Hall Effect switches with Rapid Trigger technology: reset keys instantly the moment your finger lifts upward.', specs: { Switches: 'Gateron x Lekker Hall Effect Magnetic Switches', RapidTrigger: '0.1mm to 4.0mm customizable actuation depth', Polling: '8000Hz polling rate with < 1ms input latency', Layout: '60% compact tournament layout with aluminum plate' }, rating: 5.0, numReviews: 135, isFeatured: true },
  { title: 'Razer Huntsman V3 Pro Tenkeyless Keyboard', brand: 'Razer', category: 'gaming-gear', price: 219, discountPrice: 199, stock: 25, images: [IMG.mechanical_keyboard, IMG.gaming_mouse], description: 'Gen-2 Analog Optical Switches with rapid trigger adjustment onboard via multi-function digital dial and LED array indicator.', specs: { Switches: 'Razer Analog Optical Gen-2 with Rapid Trigger', Actuation: 'Adjustable from 0.1mm to 4.0mm in 0.1mm increments', Keycaps: 'Textured Doubleshot PBT Keycaps', WristRest: 'Magnetic firm leatherette ergonomic wrist support' }, rating: 4.7, numReviews: 68 },
  { title: 'Elgato Stream Deck XL (32 LCD Keys)', brand: 'Elgato', category: 'gaming-gear', price: 249, discountPrice: 229, stock: 30, images: [IMG.stream_setup, IMG.mechanical_keyboard], description: '32 customizable studio-grade LCD keys for one-touch control over OBS Studio, Twitch, YouTube, Spotify, and smart lights.', specs: { Keys: '32 tactile keys with customizable full-color LCD screens', Stand: 'Magnetic non-slip anti-shake desktop stand', Connectivity: 'Detachable braided USB-C to USB-A cable', Compatibility: 'macOS and Windows deep software integration' }, rating: 4.9, numReviews: 195 },
  { title: 'Razer DeathAdder V3 Pro Ergonomic Wireless Mouse', brand: 'Razer', category: 'gaming-gear', price: 149, discountPrice: 134, stock: 40, images: [IMG.gaming_mouse, IMG.mechanical_keyboard], description: 'Iconic ergonomic palm grip refined by top esports athletes, weighing only 63g with Focus Pro 30K Optical Sensor.', specs: { Weight: '63g ultra-lightweight ergonomic shape', Sensor: 'Focus Pro 30K Optical Sensor (99.8% resolution accuracy)', Switches: 'Optical Mouse Switches Gen-3 rated for 90M clicks' }, rating: 4.8, numReviews: 142 },
  { title: 'Secretlab TITAN Evo Gaming Chair (Black³ SoftWeave Plus)', brand: 'Secretlab', category: 'gaming-gear', price: 549, discountPrice: 519, stock: 18, images: [IMG.stream_setup, IMG.curved_monitor], description: 'Ergonomic gaming throne featuring 4-way L-ADAPT internal lumbar support and magnetic memory foam head pillow with cooling gel.', specs: { Upholstery: 'SoftWeave Plus breathable technical fabric', Lumbar: 'Proprietary 4-Way L-ADAPT Lumbar System', Armrests: 'Full-metal 4D armrests with CloudSwap magnetic top system', Recline: '165-degree tilt mechanism with multi-tilt lock' }, rating: 4.9, numReviews: 320 },
  { title: 'Sony PlayStation 5 Slim Console (1TB SSD)', brand: 'Sony', category: 'gaming-gear', price: 499, discountPrice: 479, stock: 30, images: [IMG.gaming_phone, IMG.stream_setup], description: 'Slimmer PS5 form factor with integrated 1TB high-speed NVMe SSD and DualSense wireless controller with adaptive triggers.', specs: { CPU: 'Custom 8-core AMD Zen 2, up to 3.5 GHz variable frequency', GPU: 'Custom RDNA 2 with Ray Tracing acceleration (10.3 TFLOPs)', Storage: '1TB Ultra-High Speed Custom SSD (5.5 GB/s raw)', Haptics: 'DualSense Wireless Controller with haptic feedback' }, rating: 4.9, numReviews: 540, isFeatured: true },
  { title: 'Xbox Series X 1TB Gaming Console', brand: 'Microsoft', category: 'gaming-gear', price: 499, discountPrice: 469, stock: 25, images: [IMG.stream_setup, IMG.rtx_gpu], description: 'True 4K 120 FPS gaming with Xbox Velocity Architecture, 12 teraflops of GPU horsepower, and Quick Resume across multiple games.', specs: { Processing: 'Custom AMD Zen 2 8-core 3.8 GHz CPU', Graphics: '12 TFLOPS, 52 CUs @ 1.825 GHz Custom RDNA 2 GPU', TargetPerformance: 'True 4K at up to 120 FPS, 8K HDR support' }, rating: 4.8, numReviews: 290 },
  { title: 'Alienware 34" Curved QD-OLED Monitor (AW3423DWF)', brand: 'Alienware', category: 'gaming-gear', price: 899, discountPrice: 799, stock: 14, images: [IMG.curved_monitor, IMG.stream_setup], description: 'Quantum Dot OLED display featuring 1800R curved immersive wide canvas, 165Hz refresh rate, and 0.1ms true gray-to-gray response.', specs: { Panel: '34.18" Quantum Dot OLED 1800R curve', Resolution: 'WQHD (3440 x 1440)', Contrast: 'Infinite 1,000,000:1 contrast ratio with VESA DisplayHDR True Black 400' }, rating: 4.9, numReviews: 118 },
  { title: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard', brand: 'Keychron', category: 'gaming-gear', price: 199, discountPrice: 179, stock: 20, images: [IMG.mechanical_keyboard, IMG.stream_setup], description: 'CNC full aluminum 75% barebone mechanical keyboard with double-gasket design, Bluetooth 5.1, and QMK/VIA key remapping support.', specs: { Body: 'Full CNC machined 6063 aluminum body', Design: 'Double-Gasket Acoustic dampening construction', Switches: 'K Pro Red linear pre-lubed mechanical switches (Hot-swappable)', Keycaps: 'KSA double-shot PBT keycaps' }, rating: 4.8, numReviews: 87 },
  { title: 'Corsair K100 RGB Optical-Mechanical Keyboard', brand: 'Corsair', category: 'gaming-gear', price: 249, discountPrice: 219, stock: 22, images: [IMG.mechanical_keyboard, IMG.gaming_mouse], description: 'Hyper-processing Corsair AXON technology with 4,000Hz native polling, iCUE control wheel, and OPX optical switches.', specs: { Switches: 'Corsair OPX Optical-Mechanical (1.0mm actuation, 150M clicks)', PollingRate: '4,000Hz Hyper-polling with AXON processor', Peripherals: '6 dedicated programmable macro keys with Elgato Stream Deck integration' }, rating: 4.7, numReviews: 104 },
  { title: 'SteelSeries Apex Pro TKL Wireless (2023)', brand: 'SteelSeries', category: 'gaming-gear', price: 249, discountPrice: 229, stock: 18, images: [IMG.mechanical_keyboard, IMG.gaming_mouse], description: 'OmniPoint 2.0 adjustable magnetic switches with Rapid Trigger and built-in Smart OLED display for Discord & stats.', specs: { Switches: 'OmniPoint 2.0 Adjustable HyperMagnetic switches (0.2mm - 3.8mm)', Screen: 'OLED Smart Display delivers info straight from games & apps', Connectivity: 'Quantum 2.0 Dual Wireless (2.4GHz & Bluetooth 5.0)' }, rating: 4.8, numReviews: 69 },
  { title: 'Logitech G915 LIGHTSPEED Wireless RGB Mechanical Keyboard', brand: 'Logitech G', category: 'gaming-gear', price: 249, discountPrice: 199, stock: 35, images: [IMG.mechanical_keyboard, IMG.gaming_mouse], description: 'Ultra-thin 22mm aircraft-grade aluminum alloy design with low-profile high-performance mechanical GL switches.', specs: { Profile: '22mm ultra-slim low profile design', Switches: 'GL Clicky / GL Tactile / GL Linear mechanical switches', Battery: '30 hours continuous gaming with full RGB illumination' }, rating: 4.7, numReviews: 160 },
  { title: 'Razer Kiyo Pro Ultra 4K Streaming Webcam', brand: 'Razer', category: 'gaming-gear', price: 299, discountPrice: 269, stock: 16, images: [IMG.stream_setup, IMG.curved_monitor], description: 'The largest sensor ever in a webcam (massive 1/1.2" Sony STARVIS 2 sensor) with F/1.7 aperture for DSLR-like natural bokeh in 4K.', specs: { Sensor: 'Massive 1/1.2" Sony STARVIS 2 sensor', Resolution: 'Uncompressed 4K 30FPS or 1080P 60FPS HDR', Lens: 'Ultra-large F/1.7 aperture lens with laser auto-focus', Audio: 'Omnidirectional microphone with speech enhancement' }, rating: 4.8, numReviews: 43 },
  { title: 'Artisan Hayate Otsu FX Soft Gaming Mousepad (XL)', brand: 'Artisan', category: 'gaming-gear', price: 69, discountPrice: 59, stock: 45, images: [IMG.gaming_mouse, IMG.mechanical_keyboard], description: 'Handcrafted in Japan, widely considered the holy grail esports mousepad providing seamless gliding with pinpoint stopping control.', specs: { Size: 'XL (490 x 420 x 4 mm)', Surface: 'Jacquard weave textured polyester fabric', Base: 'Special structure single-bubble poron rubber (zero-slip suction)', Origin: 'Made in Kobe, Japan' }, rating: 5.0, numReviews: 115 },
];

// ─── HELPERS ─────────────────────────────────────────────────────────────────
function generateSlug(text) {
  return text.toString().toLowerCase().trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// ─── SEED DATABASE ───────────────────────────────────────────────────────────
async function seedDatabase() {
  try {
    console.log('\n==================================================');
    console.log('🔄 Connecting to MongoDB Atlas...');
    console.log('==================================================\n');

    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB successfully.');

    // Check for --destroy flag
    if (process.argv.includes('--destroy')) {
      console.log('🗑️  Destroying all data...');
      await Product.deleteMany({});
      await User.deleteMany({});
      console.log('💥 All data destroyed.');
      await mongoose.connection.close();
      process.exit(0);
    }

    // Clear existing data
    console.log('🗑️  Clearing existing data...');
    await Product.deleteMany({});
    await User.deleteMany({});
    console.log('🧹 Collections cleared.');

    // ── Create Admin User ────────────────────────────────────────
    console.log('👤 Creating admin user...');
    const salt = await bcrypt.genSalt(12);
    const hashedPassword = await bcrypt.hash('Admin@123', salt);

    await User.create({
      name: 'Admin',
      email: 'admin@techvault.com',
      password: hashedPassword,
      role: 'admin',
      isActive: true,
    });
    console.log('✅ Admin user created:');
    console.log('   📧 Email: admin@techvault.com');
    console.log('   🔑 Password: Admin@123');
    console.log('   👑 Role: admin');

    // ── Create Test User ─────────────────────────────────────────
    const userHashedPassword = await bcrypt.hash('User@123', salt);
    await User.create({
      name: 'Test User',
      email: 'user@techvault.com',
      password: userHashedPassword,
      role: 'user',
      isActive: true,
    });
    console.log('✅ Test user created:');
    console.log('   📧 Email: user@techvault.com');
    console.log('   🔑 Password: User@123');

    // ── Seed Products ────────────────────────────────────────────
    console.log(`\n📦 Formatting ${rawCatalog.length} realistic tech items...`);
    const formattedProducts = rawCatalog.map((item, index) => ({
      ...item,
      slug: `${generateSlug(item.title)}-${index + 101}`,
    }));

    console.log(`🚀 Inserting ${formattedProducts.length} products with 4K assets...`);
    const inserted = await Product.insertMany(formattedProducts);

    console.log('\n==================================================');
    console.log(`🎉 SUCCESS! Seeded ${inserted.length} products + 2 users!`);
    console.log('==================================================');
    console.log('📊 Category Breakdown:');
    const counts = {};
    inserted.forEach((p) => { counts[p.category] = (counts[p.category] || 0) + 1; });
    console.table(counts);

    await mongoose.connection.close();
    console.log('🔌 Connection closed. Seeder finished.');
    process.exit(0);
  } catch (error) {
    console.error('\n❌ Seeding Error:', error);
    if (mongoose.connection.readyState !== 0) await mongoose.connection.close();
    process.exit(1);
  }
}

seedDatabase();
